CREATE TABLE USERS (
    id_user NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name_user VARCHAR2(100) NOT NULL,
    email VARCHAR2(100) UNIQUE NOT NULL,
    password_hash VARCHAR2(255) NOT NULL,
    gender VARCHAR2(100) NOT NULL,
    birth_date DATE NOT NULL,
    role_account VARCHAR2(20) DEFAULT 'USER' NOT NULL,
    profile_image_url VARCHAR2(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE SESSIONS (
    id_session NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    session_token VARCHAR2(255) UNIQUE NOT NULL,
    id_user NUMBER NOT NULL,
    expires TIMESTAMP NOT NULL,
    CONSTRAINT fk_user_session FOREIGN KEY (id_user) REFERENCES USERS (id_user) ON DELETE CASCADE
);

CREATE TABLE PET (
    id_pet NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    id_user NUMBER NOT NULL,
    name_pet VARCHAR2(100) NOT NULL,
    species VARCHAR2(50) NOT NULL,
    breed VARCHAR2(100),
    birth_date DATE NOT NULL,
    diseases VARCHAR2(100),
    notes VARCHAR2(255),
    pet_image_url VARCHAR2(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_pet_user FOREIGN KEY (id_user) REFERENCES USERS (id_user) ON DELETE CASCADE,
    CONSTRAINT chk_species CHECK (species IN ('PERRO', 'GATO', 'CONEJO', 'PAJARO', 'OTHER'))
);

CREATE TABLE HEALTH_EVENT (
    id_event NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    id_pet NUMBER NOT NULL,
    event_type VARCHAR2(100) NOT NULL, 
    title VARCHAR2(100) NOT NULL,
    event_date TIMESTAMP NOT NULL,
    event_place VARCHAR2(255) NOT NULL,
    next_due_date TIMESTAMP,
    status VARCHAR2(100) DEFAULT 'SCHEDULED' NOT NULL,
    CONSTRAINT fk_event_pet FOREIGN KEY (id_pet) REFERENCES PET (id_pet) ON DELETE CASCADE,
    CONSTRAINT chk_status CHECK (status IN ('COMPLETED', 'SCHEDULED', 'CANCELLED')),
    CONSTRAINT chk_event_type CHECK (event_type IN ('VACUNA', 'CONTROL', 'DESPARACITACION', 'CIRUGIA', 'OTHER')),
    CONSTRAINT chk_date CHECK (next_due_date > event_date)
);
